# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Template
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  A Template project for Jekyll and Github Pages
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

app:
  links:
    footer:
      agency:
        hhs: https://www.hhs.gov/
        usa: https://www.usa.gov/
        disclaimer: https://www.cdc.gov/Other/disclaimer.html
      cdc:
        info:
          about: https://www.cdc.gov/about/default.htm
          jobs: https://jobs.cdc.gov/
          funding: https://www.cdc.gov/funding
          policies: https://www.cdc.gov/Other/policies.html
          viewers: https://www.cdc.gov/other/plugins/index.html
          privacy: https://www.cdc.gov/Other/policies.html
          FOIA: https://www.cdc.gov/od/foia
          nofear: https://www.cdc.gov/eeo/nofearact/index.htm
          OIG: https://oig.hhs.gov/
          nondisc: https://www.cdc.gov/other/nondiscrimination.html
          access: https://www.cdc.gov/contact/accessibility.html
        connect:
          facebook: https://www.facebook.com/CDC
          twitter: https://twitter.com/CDCgov
          youtube: https://www.youtube.com/user/CDCstreamingHealth
          instagram: https://www.instagram.com/CDCgov/
          # syndicate: https://tools.cdc.gov/medialibrary/index.aspx#/sharecontent/[URL]
          cdctv: https://www.cdc.gov/cdctv
          rss: https://tools.cdc.gov/podcasts/rss.asp
          contact: https://wwwn.cdc.gov/dcs/RequestForm.aspx
  site:
    isDevTarget: false



repository: "peterbenoit/bs4ghp"

# Build settings
plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
